//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacenamiento
    {
        public int idAlmacenamiento { get; set; }
        public int idConfiguracion { get; set; }
        public string ruta { get; set; }
        public string contrasenia { get; set; }
    
        public virtual configuracion configuracion { get; set; }
    }
}
