//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class backupEntities : DbContext
    {
        public backupEntities()
            : base("name=backupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<almacenamiento> almacenamiento { get; set; }
        public DbSet<archivo> archivo { get; set; }
        public DbSet<configuracion> configuracion { get; set; }
        public DbSet<directorio> directorio { get; set; }
        public DbSet<movimiento> movimiento { get; set; }
        public DbSet<registro> registro { get; set; }
        public DbSet<repositorio> repositorio { get; set; }
        public DbSet<respaldo> respaldo { get; set; }
        public DbSet<tipomovimiento> tipomovimiento { get; set; }
        public DbSet<tipousuario> tipousuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<usuariorepositorio> usuariorepositorio { get; set; }
    }
}
