//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class backupEntities : DbContext
    {
        public backupEntities()
            : base("name=backupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<almacenamiento> almacenamientoes { get; set; }
        public DbSet<archivo> archivoes { get; set; }
        public DbSet<configuracion> configuracions { get; set; }
        public DbSet<directorio> directorios { get; set; }
        public DbSet<movimiento> movimientoes { get; set; }
        public DbSet<registro> registroes { get; set; }
        public DbSet<repositorio> repositorios { get; set; }
        public DbSet<respaldo> respaldoes { get; set; }
        public DbSet<tipomovimiento> tipomovimientoes { get; set; }
        public DbSet<tipousuario> tipousuarios { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<usuariorepositorio> usuariorepositorios { get; set; }
    }
}
