//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public configuracion()
        {
            this.almacenamientoes = new HashSet<almacenamiento>();
            this.directorios = new HashSet<directorio>();
            this.repositorios = new HashSet<repositorio>();
        }
    
        public int idConfiguracion { get; set; }
        public int idRespaldo { get; set; }
        public Nullable<int> incremento { get; set; }
        public Nullable<System.DateTime> fechaEdicion { get; set; }
    
        public virtual ICollection<almacenamiento> almacenamientoes { get; set; }
        public virtual respaldo respaldo { get; set; }
        public virtual ICollection<directorio> directorios { get; set; }
        public virtual ICollection<repositorio> repositorios { get; set; }
    }
}
