//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public configuracion()
        {
            this.almacenamiento = new HashSet<almacenamiento>();
            this.directorio = new HashSet<directorio>();
            this.proyecto = new HashSet<proyecto>();
            this.repositorio = new HashSet<repositorio>();
        }
    
        public int idConfiguracion { get; set; }
        public string incremento { get; set; }
        public Nullable<System.DateTime> fechaEdicion { get; set; }
    
        public virtual ICollection<almacenamiento> almacenamiento { get; set; }
        public virtual ICollection<directorio> directorio { get; set; }
        public virtual ICollection<proyecto> proyecto { get; set; }
        public virtual ICollection<repositorio> repositorio { get; set; }
    }
}
