//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public int idMovimiento { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public string descripcionMovimiento { get; set; }
        public int idTipoMovimiento { get; set; }
        public int idRepositorio { get; set; }
    
        public virtual repositorio repositorio { get; set; }
        public virtual tipomovimiento tipomovimiento { get; set; }
    }
}
