//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int idRegistro { get; set; }
        public int idRepositorio { get; set; }
        public string versionDefault { get; set; }
        public string versionNominal { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        public virtual repositorio repositorio { get; set; }
    }
}
