//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class repositorio
    {
        public repositorio()
        {
            this.movimientoes = new HashSet<movimiento>();
            this.registroes = new HashSet<registro>();
            this.usuariorepositorios = new HashSet<usuariorepositorio>();
        }
    
        public int idRepositorio { get; set; }
        public int idConfiguracion { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string versionEstable { get; set; }
    
        public virtual configuracion configuracion { get; set; }
        public virtual ICollection<movimiento> movimientoes { get; set; }
        public virtual ICollection<registro> registroes { get; set; }
        public virtual ICollection<usuariorepositorio> usuariorepositorios { get; set; }
    }
}
