//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class respaldo
    {
        public respaldo()
        {
            this.configuracion = new HashSet<configuracion>();
        }
    
        public int idRespaldo { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public string direccion { get; set; }
        public string ruta { get; set; }
    
        public virtual ICollection<configuracion> configuracion { get; set; }
    }
}
