//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackUProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.registro = new HashSet<registro>();
            this.usuariorepositorio = new HashSet<usuariorepositorio>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string contrasenia { get; set; }
    
        public virtual ICollection<registro> registro { get; set; }
        public virtual ICollection<usuariorepositorio> usuariorepositorio { get; set; }
    }
}
